# Site settings
title: A personal web
description: Alfredo Talavera Ramajo
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alfredo Talavera Ramajo
user_description: Software Developer / Network Administrator / Big data and Artificial Intelligent Specialist
user_title: Software Developer / Network Administrator / Big data and Artificial Intelligent Specialist
email: alfredo98norba@gmail.com
twitter_username: Freddiie_Works
github_username:  dev-freddiies
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
